/**
 * Props for the TextInput component.
 * ----------------------------------
 * Defines the contract for a controlled or uncontrolled text input component
 * that notifies its parent whenever the user types.
 *
 * @property onTextChange - Callback invoked whenever the textarea value changes.
 *                          Receives the updated text as a string.
 *
 * @property placeholder - Optional placeholder text displayed when the input is empty.
 *
 * @property initialValue - Optional initial value for the textarea. Used only on
 *                          first render when the component is uncontrolled.
 */
export interface TextInputProps {
    onTextChange: (text: string) => void;
    placeholder?: string;
    initialValue?: string;
}

/**
 * Represents computed statistics about a block of text.
 * ------------------------------------------------------
 * These values are generated by the CharacterCounter component and passed
 * to StatsDisplay for rendering.
 *
 * @property characterCount - Total number of characters in the text.
 *
 * @property wordCount - Total number of words in the text.
 *
 * @property readingTime - Estimated reading time in minutes (decimal).
 */
export interface TextStats {
    characterCount: number;
    wordCount: number;
    readingTime: number; // in minutes
}

/**
 * Props for the StatsDisplay component.
 * -------------------------------------
 * Defines the data required to render text statistics and optional styling.
 *
 * @property stats - Object containing character count, word count, and reading time.
 *
 * @property showReadingTime - Whether the reading time section should be displayed.
 *
 * @property color - Tailwind CSS class applied to the word count value. Allows the
 *                   parent component to dynamically style the counter based on rules.
 */
export interface StatsDisplayProps {
    stats: TextStats;
    showReadingTime?: boolean;
    color?: string
}

/**
 * Props for the CharacterCounter component.
 * -----------------------------------------
 * Defines configuration values used to evaluate text input and compute statistics.
 *
 * @property minWords - Minimum number of words required. Used for validation and styling.
 *
 * @property maxWords - Maximum number of words allowed. Used for validation and styling.
 *
 * @property targetReadingTime - Reading speed in words per minute. Used to compute
 *                               estimated reading time.
 */
export interface CharacterCounterProps {
    minWords?: number;
    maxWords?: number;
    targetReadingTime?: number; // in minutes
}